### ISSUE TITLE
Questions / Suggestions (JOSS review)

### ISSUE THREAD

**Issue by mancellin** [jnoynaert/PressureDrop.jl#3]
Hi @jnoynaert 
Here are a few friendly suggestions that came to my mind while reviewing your package for the JOSS.

- The documentation would be more friendly to beginners if it included an example of `surveyfilepath` and `valvefilepath`.
- I could not easily find information about the theory behind your code: which equations are being solved and the method used. Adding a short summary of the theory in the documentation could be nice. For instance, from reading the code, it seems that the core functions of the code are using some Picard fixed point iterative method, am I right ?
- About this iterative method, a possible improvement would be to call a dedicated Julia library. It would make the code more powerful for advanced users and would fit within your goals of modularity and composability.
- The JOSS paper might be a good place to cite the other packages your code is relying on. [Gadfly's documentation](http://gadflyjl.org/stable/) suggests a citation for their package.

**Comment by jnoynaert** [comment]
Thanks! File paths are exactly the sort of thing that would trip up a lot of the target users. 

I'll add some reference to the basic theory; you're correct that the solution is just fixed-point iteration. The level of effort to utilize NLPsolve.jl for the solutions should be pretty reasonable, so I'll try that out in a test branch.

**Comment by mancellin** [comment]
> File paths are exactly the sort of thing that would trip up a lot of the target users.

To clarify, I was thinking of providing examples of the content of the files. Although, you could also add examples of the paths themselves.

**Comment by jnoynaert** [comment]
That would, indeed, be much more useful than a file path example...!

I really liked your idea of of using a dedicated solver library, so I tested using NLsolve.jl to calculate the solution of each pressure segment:
- This seemed like the most reasonable dedicated package for this purpose, other than treating it as optimization problem via JuMP.jl or similar. 
- I ended up dropping the change, as using Anderson acceleration with a variety of tweaks actually made things both slower and less stable, while just using the NLsolve equivalent of naive fixed-point (Anderson with 0 memory) just made things slower.
    - After investigating this, I think the issue is that across all test cases, the maximum number of iterations to converge for a segment turned out to be 5 (more typically 2-3). Thus the overhead of more advanced methods doesn't pay out, and wrappers over the naive method don't offer any improvement either.
- The very positive outcome of this line of investigation was that in the process of refactoring functions to match NLsolve's expected input, a few performance easy performance optimizations became obvious, so now most cases will run 15-20% faster :)

When I have time I'll implement the changes to the paper & documentation that you suggested, and tag you once that's complete.

**Comment by jnoynaert** [comment]
@mancellin I've implemented the suggested changes:
- added Gadfly citation to paper
- added some very high level notes on the theory on [the documentation landing page](https://jnoynaert.github.io/PressureDrop.jl/stable/)
- added some file format examples in [the documentation](https://jnoynaert.github.io/PressureDrop.jl/stable/core/#Wellbores-1) as well as links to example files in the readme

Let me know if you have any other suggestions!

**Comment by mancellin** [comment]
Great!

The new overview in the documentation is very helpful. So, the big picture of your problem is actually a non-linear ODE. Maybe you should then check DifferentialEquations.jl instead of NLSolve.

One more thing: the use of non-SI units feels a bit weird to me. But I guess it is standard in your industry, isn't it?

**Comment by jnoynaert** [comment]
Non-SI units are indeed the standard in the U.S., even for academia. Outside the U.S. typical SI units are also common, but things can get stranger (reporting oil in metric tons in Russia, for example).

I'll look into using DiffEq.jl for the solution--that's an attractive idea because I think I might be able to formulate it so that I get a solution along the entire flow path in a single call instead of iterating by segment.

Thanks for the input!

**Comment by wkearn** [comment]
It seems like you added filepaths to the documentation, e.g.

```
valvefilepath = joinpath(dirname(dirname(pathof(PressureDrop))), "test/testdata/valvedata_wrappers_1.csv"
```

It would be nice if you duplicated that in the README. A potential user could then copy and paste the code example from the README and run it successfully.

The other suggestion I have would be a comparison between the model output from PressureDrop.jl and one of the commercial packages mentioned in the paper, like a plot showing that the output from PressureDrop.jl is more or less identical to the software people might otherwise use.

**Comment by jnoynaert** [comment]
Great ideas; I'll add both of those.

**Comment by jnoynaert** [comment]
@wkearn I finally made the updates to the readme & documentation; see [here](https://jnoynaert.github.io/PressureDrop.jl/v1.0/similartools/) for a comparison table and a visual comparison to one of the more popular tools.

As far as numerical output comparisons go, a whole section of integration testing is validated against outputs from a commercial package (the other sections coming from reference texts)

**Comment by wkearn** [comment]
Sorry for the delay. This looks great!
